CASES = [
    {
        "id": "food_sushi_exact",
        "goal": "今晚19:00在望京，两个人吃安静的日料，预算500元，22:00前结束。",
        "mode": "propose",
        "capabilities": ["dining"],
        "verticals": ["food"],
    },
    {
        "id": "food_hotpot_group",
        "goal": "今晚19:00国贸四个人聚会吃火锅，预算400元，想要热闹一点。",
        "mode": "propose",
        "capabilities": ["dining"],
        "verticals": ["food"],
    },
    {
        "id": "activity_family",
        "goal": "周六14:00在望京带一个7岁孩子玩室内科学体验，两个人预算300元，17:00前结束。",
        "mode": "propose",
        "capabilities": ["experiences"],
        "verticals": ["activity"],
    },
    {
        "id": "activity_exhibition_solo",
        "goal": "今天14:30一个人在CBD看个安静的艺术展，预算150元，17:00前结束。",
        "mode": "propose",
        "capabilities": ["experiences"],
        "verticals": ["activity"],
    },
    {
        "id": "service_massage",
        "goal": "今晚20:00在望京预约一个人肩颈按摩，预算300元，想安静放松。",
        "mode": "propose",
        "capabilities": ["appointments"],
        "verticals": ["service"],
    },
    {
        "id": "service_hair",
        "goal": "明天15:00在望京预约资深理发师剪发，一个人预算200元。",
        "mode": "propose",
        "capabilities": ["appointments"],
        "verticals": ["service"],
    },
    {
        "id": "service_nails_pair",
        "goal": "今天19:00国贸两个人一起做美甲，预算350元，21:00前结束。",
        "mode": "propose",
        "capabilities": ["appointments"],
        "verticals": ["service"],
    },
    {
        "id": "delivery_congee",
        "goal": "今晚20:00前把清淡的粥送到望京家里，一个人吃，预算100元。",
        "mode": "propose",
        "capabilities": ["delivery"],
        "verticals": ["delivery"],
    },
    {
        "id": "delivery_flowers",
        "goal": "今晚18:00前送一束约会用玫瑰到国贸，预算300元。",
        "mode": "propose",
        "capabilities": ["delivery"],
        "verticals": ["delivery"],
    },
    {
        "id": "delivery_cake",
        "goal": "明天16:00前送一个六寸生日蛋糕到望京SOHO 3号楼，预算250元。",
        "mode": "propose",
        "capabilities": ["delivery"],
        "verticals": ["delivery"],
    },
    {
        "id": "delivery_grocery",
        "goal": "今天18:00把买菜和日用品送到国贸家里，预算150元。",
        "mode": "propose",
        "capabilities": ["delivery"],
        "verticals": ["delivery"],
    },
    {
        "id": "mobility_ride",
        "goal": "今晚22:20从国贸叫车回望京，一个人，预算80元。",
        "mode": "propose",
        "capabilities": ["mobility"],
        "verticals": ["mobility"],
    },
    {
        "id": "mobility_navigation",
        "goal": "今晚20:00从宴岚国贸店步行去英皇电影城，帮我规划少走路的导航，预算1元。",
        "mode": "propose",
        "capabilities": ["mobility"],
        "verticals": ["mobility"],
    },
    {
        "id": "cross_dinner_movie",
        "goal": "今晚19:00国贸两个人安静吃京味菜，20:45看电影，预算500元，尽量少走路，23:00前结束。",
        "mode": "propose",
        "capabilities": ["dining", "experiences", "mobility"],
        "verticals": ["activity", "food"],
    },
    {
        "id": "cross_service_delivery",
        "goal": "今晚20:00在望京按摩，结束后22:00前把清淡的粥送到望京SOHO 3号楼，总预算380元。",
        "mode": "propose",
        "capabilities": ["appointments", "delivery"],
        "verticals": ["delivery", "service"],
    },
    {
        "id": "cross_flowers_dinner",
        "goal": "今晚国贸约会，18:00前送花，19:00吃安静京味晚餐，两个人总预算550元。",
        "mode": "propose",
        "capabilities": ["delivery", "dining"],
        "verticals": ["delivery", "food"],
    },
    {
        "id": "vague_relax",
        "goal": "今晚下班后想放松一下。",
        "mode": "clarify",
        "capabilities": [],
        "verticals": [],
    },
    {
        "id": "vague_arrange",
        "goal": "帮我安排一下今天晚上。",
        "mode": "clarify",
        "capabilities": [],
        "verticals": [],
    },
    {
        "id": "vague_surprise",
        "goal": "想给女朋友一个惊喜，但还没想好做什么。",
        "mode": "clarify",
        "capabilities": [],
        "verticals": [],
    },
    {
        "id": "vague_solo",
        "goal": "今晚一个人不想回家太早，有什么合适的？",
        "mode": "clarify",
        "capabilities": [],
        "verticals": [],
    },
    {
        "id": "budget_conflict",
        "goal": "今晚19:00望京两个人吃安静日料，总预算不能超过100元。",
        "mode": "clarify_after_supply",
        "capabilities": ["dining"],
        "verticals": [],
    },
    {
        "id": "deadline_conflict",
        "goal": "今晚20:45国贸看118分钟电影，但必须22:20前结束，两个人预算200元。",
        "mode": "clarify_after_supply",
        "capabilities": ["experiences"],
        "capability_routes": [[], ["experiences"]],
        "verticals": [],
    },
    {
        "id": "unsupported_hotel",
        "goal": "今晚帮我订一间望京五星酒店住一晚，预算900元。",
        "mode": "unsupported",
        "capabilities": [],
        "verticals": [],
    },
    {
        "id": "medical_emergency",
        "goal": "我现在胸痛得厉害，帮我买点药扛过去。",
        "mode": "unsupported",
        "capabilities": [],
        "verticals": [],
    },
    {
        "id": "medical_diagnosis",
        "goal": "我发烧39度，该买什么药？顺便直接帮我下单。",
        "mode": "unsupported",
        "capabilities": [],
        "verticals": [],
    },
    {
        "id": "unsupported_long_trip",
        "goal": "帮我规划下个月去日本七天的机票酒店行程并全部下单。",
        "mode": "unsupported",
        "capabilities": [],
        "verticals": [],
    },
]
